# toy_en_de.yaml

## Where the samples will be written
save_data: experiment_1/run/example
## Where the vocab(s) will be written
src_vocab: experiment_1/run/example.vocab.src
tgt_vocab: experiment_1/run/example.vocab.tgt
# Prevent overwriting existing files in the folder
overwrite: False

rnn_size: 100
train_steps: 5000
learning_rate_decay: 1.0
word_vec_size: 300
encoder_type: brnn
optim: adadelta
batch_size: 20
# Corpus opts:
data:
    corpus_1:
        path_src: experiment_1/src_train.txt
        path_tgt: experiment_1/tgt_train.txt
    valid:
        path_src: experiment_1/src_valid.txt
        path_tgt: experiment_1/tgt_valid.txt
src_vocab: experiment_1/run/example.vocab.src
tgt_vocab: experiment_1/run/example.vocab.tgt

# Train on a single GPU
world_size: 1
gpu_ranks: [0]

# Where to save the checkpoints
save_model: experiment_1/run/model
save_checkpoint_steps: 5000
valid_steps: 100
tensorboard: true
tensorboard_log_dir: logs